### ISSUE TITLE
Help "?" popup hiding when in half-screen window resizing

### ISSUE THREAD

**Issue by thepragmaticmero** [cockpit-project/cockpit-machines#1794]
An image is worth a thousand words.
![image](https://github.com/user-attachments/assets/93506312-53f1-4ded-bc6d-586f7dfb5706)

The popup should be above the left-panel, not behind it

**Comment by garrett** [comment]
It's impossible for the popover to show above the left-panel, as that is a different page (the shell, versus the iframe which has the document with the popover).

The correct solution would be to have the popover account for the left side of the page.

There's a setting in PF @ https://www.patternfly.org/components/popover/#popover:

> **enableFlip**
> boolean:	true
> If true, tries to keep the popover in view by flipping it if necessary. If the position is set to 'auto', this prop is ignored.

However, I think that just flips left/right, and this is on top.

We could have the popover to the right in smaller modes... but then that'd cover up the options the popover is talking about. Below would also not work as expected. Ideally, we'd still be able to have it on the top, but with the popover slide over to the side (with the pointer in the same place).

I'm not sure if this is a PF issue or not. It _should_ stay in the page by default.

**Comment by garrett** [comment]
Interestingly, in desktop mode, I see it pops up over to the right already: 
![image](https://github.com/user-attachments/assets/9b9441aa-02f8-4aca-b3c9-b3784ef6a038)

It only shows up on top in small sizes:
![Screen Shot 2024-09-02 at 15 21 06](https://github.com/user-attachments/assets/ba168efc-6106-4301-9a9b-07a6429805d5)

Even odder, there's a small bit of width in-between where it's on top and it does slide over... I think this is actually what we'd want in smaller sizes:
![image](https://github.com/user-attachments/assets/5b754cfb-ec4e-4254-8846-b9311fa1e031)
(Although the arrow is misaligned a bit, it's mostly around the right location.)

**Comment by thepragmaticmero** [comment]
yeah, I'm using a tiling window manager on ArchLinux and Fedora, so my windows are 1/2 or 1/3 of my whole screen, problems with window reactivity aren´t really uncommon in the JS world. Anyways, let's wait for a fix then, for now I'll zoom out of the page.

**Comment by garrett** [comment]
PatternFly has an `appendTo` value for popovers @ https://www.patternfly.org/components/popover/#props — using this _might_ help with the positioning for both vsock and watchdog (?) icons. 

Meanwhile, this bug was _supposed to_ have been fixed in PF some time ago:

- https://github.com/patternfly/patternfly/issues/4754
- https://github.com/patternfly/patternfly-react/issues/7762

But, it obviously is still an issue here, regardless of the state in PF and PF-React... so the problem still exists, of course.

**Comment by mvollmer** [comment]
It's still the same with PF6:

<img width="850" height="635" alt="Image" src="https://github.com/user-attachments/assets/86b4b4d7-d886-4cde-a043-205dc8c1fcb0" />

We could make the popup less wide.
