### ISSUE TITLE
machines: can't connect to the spice address

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit-machines#73]
Cockpit version: 183
OS: Fedora 28
Page: Machines

I have a VM running on a remote server. I wanted to connect to it using GNOME Boxes. I inputted the address it told me in Cockpit, but it didn't work.

Steps to reproduce

1. Go to the VM page in Cockpit
2. Select an existing VM and run it.
3. Go to the Consoles page
4. Copy the address there
5. Open GNOME Boxes
6. Under the Remote tab, select New and input the address.
7. Boxes fails to connect

![screenshot from 2019-02-21 12-26-45](https://user-images.githubusercontent.com/209895/53165929-3d579680-35d4-11e9-843f-95cabbe4f067.png)

![screenshot from 2019-02-21 12-25-54](https://user-images.githubusercontent.com/209895/53165938-43e60e00-35d4-11e9-81eb-dec28fd66a41.png)

![screenshot from 2019-02-21 12-26-37](https://user-images.githubusercontent.com/209895/53165948-4b0d1c00-35d4-11e9-945a-ab582866bb30.png)

**Comment by joolli** [comment]
I'm having this problem too.It seems like the remote viewing is not going through ssh like the rest of the management connection. I can enable vnc or spice to listen on 0.0.0.0 but it'd be better if it would go through SSH like in virt-manager.

**Comment by madwax** [comment]
Work around 
1) exit your hosts /etc/libvirt/qemu.conf file
2) find #spice_listen = "0.0.0.0" 
3) uncomment and put your hosts IPv4 address. (Don't know if IPv6 works)
This only works when creating a new VM (the value is read by install_machines.py)

**Comment by cameronetchart** [comment]
> Work around
> 
>     1. edit your hosts /etc/libvirt/qemu.conf file
> 
>     2. find #spice_listen = "0.0.0.0"
> 
>     3. uncomment and put your hosts IPv4 address. (Don't know if IPv6 works)
>        This only works when creating a new VM (the value is read by install_machines.py)

I have figured out how to fix this issue another way without a network card change, as @madwax's solution unfortunately did not work for me, but it inspired me where to look. 

In my example, my headless cockpit host machine (ubuntu server) is 192.168.11.10, and my manjaro VM is 192.168.11.9. I'm trying to use SPICE to connect from a separate Windows PC (using windows virt-viewer) to the manjaro VM, but using the cockpit "proxy."

- Create the VM using cockpit normally (I only use a direct attachment network driver, linked to my Cockpit server's ethernet port, so that my network issues it an IP in my normal homelab subnet)
- On the cockpit machine terminal, run "virsh edit VM-NAME-HERE"
- Look for the spice graphics portion, which will have a "listen=" entry and a "address=" entry as 127.0.0.1. Change this to the IP of your cockpit machine (mine is 192.168.11.10). I also changed this for the VNC entries above, but I haven't tested it since I don't use VNC.
![image](https://user-images.githubusercontent.com/6248778/167896136-c4db0a5f-8061-41a5-a2f9-fa2bef494364.png)

- I rebooted the VM, and SPICE works!

This solution has the side effect of making the "launch remote viewer" .vv download button in Cockpit work, as it fixes the address from the 127 address to the correct internal IP.
![image](https://user-images.githubusercontent.com/6248778/167895133-32357058-b267-447f-902d-58de41762df9.png)

**Comment by grigio** [comment]
@cameronetchart I love you! this issue is still relevant.. I should have found this hack sooner

**Comment by zalnaRs** [comment]
@cameronetchart Thank you so much! This should be fixed asap, this is the biggest thing holding cockpit back :)

**Comment by KKoukiou** [comment]
Duplicate of #1078

**Comment by testman42** [comment]
This should probably be re-opened, as the issue still persists.
At least for me (Fedora 40, cockpit 318, cockpit-machines 314).
Creating new VM results in VNC address being 127.0.0.1, and of course attempting VNC connection to <host_local_IP>:5900 does not work. 
And I am not even doing any crazy networking wizardry, just a host connected to a local network.

**Comment by maravento** [comment]
remote-viewer spice://[::1]:5901

**Comment by sirweazel** [comment]
Edit: after more research it looks like spice was intentionally removed. I still opened an issue to get more clarity.

I'm gonna open a new thread shortly with more info, but with the latest upgrade, spice appears to be using the wrong port. i can connect with virtmanager, but not via cockpit machines. It isn't reading the auto port setting correctly i think. Just curious if anyone is seeing something similar or if it's isolated to me.
